sudo: required

language: cpp

os: linux
dist: trusty

compiler: gcc

before_install:
    - sudo apt-get install -y libblas-dev
    - sudo apt-get install -y liblapacke-dev
    - sudo apt-get install -y libatlas-base-dev
